### ISSUE TITLE
Erreur de Conception, Vérification de paramètre dans les urls

### ISSUE THREAD

**Issue by NicolasDelahaigue** [Indaym/Back-Indaym#15]
Pour la vérification des paramètres dans les urls je rencontre un problème.
Voici la conception actuel
```
GameRouter ( /games ) :
  /
  /:idGame
  /:idGame/scenes => SceneRouter
SceneRouter ( /games/:idGame/scenes/ )
  /
  /:idScene
  /:idScene/scripts => ScriptRouter
  /:idScene/objects => ObjectRouter
ScriptRouter ( /games/:idGame/scenes/:idScene/scripts
  /
  /:idScript
ObjectRouter ( /games/:idGame/scenes/:idScene/objects)
  /
  /:idObject
```
Le problème étant que les paramètres dans les urls (idGame, idScene, etc) sont local au Router.
C'est à dire quand dans SceneRouter tu n'as pas accès à idGame

### Problèmes

- Pour l'instant le problème que ça cause c'est que lorsque j'effectue une requête par exemple `GET /games/42/scenes/685` et il va me vérifier l'idScene 685 mais pas l'idGame 42
- Mais l'autre problème c'est que dans SceneRouter je peux pas récupérer l'idGame donc si je veux créé une scene il va falloir que je sache dans quel game je la créé cette scene hors on a pas idGame

### Solution

- Les routers SceneRouter, ScriptRouter, ObjectRouter disparaissent pour venir ce link au router GameRouter.

Dernier commit concerné : 650a9d1

**Comment by djavrell** [comment]
comme je t'es dit sur slack:

ne fait pas de sous router, mat les de manière horizontal, c'est le seul moyen qu'on à pour le moment d'isolée des middlewares
