### ISSUE TITLE
Conflit DB

### ISSUE THREAD

**Issue by djavrell** [Indaym/Back-Indaym#18]
bon bon bon, 

Nous avons un problème mes amis,

Actuellement la DB est chez Clever-Cloud, ce qui pose certain problème lors du dev,
en effet, lorsque l'on est plusieurs à modifier les tables (et que l'on est sur different branches) avec le reload du server, ca casse les table pour tout le monde

Du coup, la solution, c'est de faire un container Docker qui contiendrait la DB, mais il faudrait la run sois même

bien évidement, les scripts seront fournies pour que ca fonctionne sans trop de problème

en plus, on pourrais faire du pré-remplissage pour différant cas sans trop de soucies

voilà voilà

**Comment by Chuwbi** [comment]
De toute façon on a pas trop le choix !
Faisons ça ! (ça fera un truc de plus sur lequel mon pc créera des bugs mystiques :D )
Et pouvoir faire du pré-remplissage c'est cool, ça va faciliter les tests j'pense :)

**Comment by NicolasDelahaigue** [comment]
Je pense que je vais poser mes jours de congé en prévision de tes bugs mystiques :'(

**Comment by waxzce** [comment]
Le mieux est de caler la conf de DB dans des variables d'env, ça simplifiera le modèle. En node je recommande cette dep : https://www.npmjs.com/package/common-env
Et après, soit booter un docker en local, soit prendre des plans dev sur clever ;-)
