### ISSUE TITLE
Lien dans le package.json

### ISSUE THREAD

**Issue by NicolasDelahaigue** [Indaym/Back-Indaym#5]
Dans le package.json les liens pointent toujours vers gitlab et non github. 
C'est le cas sur toutes les branches.

**Comment by djavrell** [comment]
bien vu l'aveugle
je m'occupe de ca, à moins que quelqu'un ai le temps de fixe ca :stuck_out_tongue_winking_eye:

**Comment by NicolasDelahaigue** [comment]
Ahah :P
Tkt c'est pas urgent juste faudra pas oublier

**Comment by NicolasDelahaigue** [comment]
Je pense que l'on peut close cette issue étant donné que le problème a été corrigé dans la PR #10
