### ISSUE TITLE
API, objectif prochain TA ?

### ISSUE THREAD

**Issue by Chuwbi** [Indaym/Back-Indaym#8]
Hello,

Mon but étant d'avoir une API fonctionnelle pour pouvoir load la bibliothèques d'items 3D de l'éditeur, et non comme c'est déjà le cas, écrire les items en dur.

Vous savez tous que depuis que colliot s'est barré comme un traitre, Kévin est tout seul à faire le back, et il a beaucoup de travail. C'est pourquoi, Nicolas pourrait basculer et aider un peu Kévin à faire l'API pendant les deux prochains mois.

Pensez-vous que cet objectif est possible ?

**Comment by djavrell** [comment]
Je suis pour
j’aimerais juste bosser sur l'auth avant, mais si Nico vient, je vois pas de soucie

je suis donc pour comme je t'es dit sur slack

**Comment by tokiplow** [comment]
Pour aussi, c'est vraiment pas la bonne idée de me laisser sur le back :(

**Comment by NicolasDelahaigue** [comment]
Au pire Kevin on bossera en parallèle toi sur l'authentification et moi sur l'api et tu me rejoindra quand tu auras fini
Si tu implémente l'authentification comme un middleware j'aurais même pas à modifier mon code pour que ça marche avec l'authentification

**Comment by NicolasDelahaigue** [comment]
Je suis dessus là. J'ai fait toute la conception pour ce suivi par contre je promet pas que toute l'Api sera implémenté pour le ta2 car il y a toute la gestion création de jeu de scène d'objets de scripts etc
Et même si le back j'arrive à le faire à temps le front sera pas fini

**Comment by NicolasDelahaigue** [comment]
Sachant que les tables dans la db ne sont pas créé donc c'est ça en plus à faire

**Comment by NicolasDelahaigue** [comment]
Les Tables dans la DB sont créé
Les urls pour /library sont faite, il me reste tout le /games mais ce sera fait pour le suivi
Il faudra que je travail pour le prochain suivi ou celui d'après sur le chargement de modèle threejs. En fonction de l'avancement du front et de l'authentification ça sera peut être pas pour le prochain suivi et l'objectif est peut être un peu gros ^^.
